### ISSUE TITLE
Add long polling feature ?

### ISSUE THREAD

**Issue by aminesig** [DigitalGlobe/jetset#11]

**Comment by glortho** [comment]
@aminesig that would be nice. on our roadmap is support for pushing via sockets when your url includes the `ws://` protocol. we'd like to look at socket.io support as well. in the meantime you can do short polling with:

```javascript
componentDidMount() {
  this.interval = setInterval(() => this.props.myResource.$list().$reset(), 1000)
}

componentWillUnmount() {
  clearInterval( this.interval )
}

render() {
  return this.props.myResource.$list().map( ... )
}
```

i know that doesn't likely support your use case, but it's something! note that you could set up this interval once in a root component, whether or not it renders `$list()` and then any other components that do render `$list()` would get the updated data on subsequent polls.

**Comment by aminesig** [comment]
Seems like a good workaround for now as I can enable that in my component code ! looking forward to the ws support !
