### ISSUE TITLE
Server side rendering [window is undefined]

### ISSUE THREAD

**Issue by g45t345rt** [DigitalGlobe/jetset#15]
This is where it fails
https://github.com/DigitalGlobe/jetset/blob/e097fe286f78bcf8ef829fa42c17587886d369e1/src/api/routes.js#L3

Commenting the line fix the issue. Maybe we could add an if statement to check if window is available?

**Comment by g45t345rt** [comment]
#16

**Comment by glortho** [comment]
Fixed as of 2.0.7.
