### ISSUE TITLE
nextjs ssr

### ISSUE THREAD

**Issue by g45t345rt** [DigitalGlobe/jetset#17]
Jetset components do not work out of the box with Next.js ssr.

Api component or ApiDecorator do not implement getInitialProps. Cache do not reset on server rendering. Meaning that changes made on client side with delete, update or create do not reflect on server side because it's not resetting the cache.

e.g.
`   

    static async getInitialProps(ctx) {

      const api = createActions({
          url: 'http://localhost:3000',
          myResource: '/resource'
      })

      await api.myResource.reset()

      // this will get serialize, so we don't pass api
      // reinitiate api in constructor to get access in render
      return { data: await api.myResource.list().data }
    }

`

Don't hesitate to comment if you don't understand what I mean.

**Comment by glortho** [comment]
@g45t345rt try `await api.myResource.list().promise`

**Comment by g45t345rt** [comment]
The code in my example is how to make it work :D I just wanted to let you know that Jetset does not work with Nextjs right away.

**Comment by glortho** [comment]
Ah okay thank you @g45t345rt -- good to know!
