### ISSUE TITLE
add an onError option to api config

### ISSUE THREAD

**Issue by glortho** [DigitalGlobe/jetset#4]

**Comment by glortho** [comment]
We'll want to support this in 3 places:

1. As a prop on `<Api>`, applicable to all fetches:

    ```jsx
    <Api onError={ error => /* do something */ }>...</Api>
    ```

1. As an option for a given resource:

    ```jsx
    <Api users={{ onError: error => /* do something */ }} ...>...</Api>
    ```

1. As an option for a given route:

    ```jsx
    const routes = {
      list: () => ({ method: 'get', route: '/list', onError: error => /* do something */ })
      ...
    }
    <Api users={{ routes }} ...>...</Api>
    ```

I don't know for sure the best approach to implementing this but there is a pattern emerging for retrieving and returning this kind of option in the `getRouteConfig` function that gets returned in src/api/routes.js, which gets called/consumed in src/api/methods.js.

**Comment by maxwell-oroark** [comment]
@glortho - awesome will dig in and take a look this evening.  Will it maybe involve adding a .catch somewhere and making sure that bubbles up through a getRouteConfig function if present?

**Comment by glortho** [comment]
@maxwell-oroark yeah we have basic error handling in place right now to set some state when `fetch` returns an error (in src/api/methods.js), so you'll likely want to pluck the handler out of the route config and call it there, but I'm not 100% sure.
